# Generated by Django 3.2.12 on 2022-04-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=200)),
                ('hometown_city', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=200)),
                ('credit_card', models.CharField(max_length=200)),
                ('credit_card_type', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('linkedin_skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_im_id', models.CharField(max_length=50)),
                ('i_name', models.CharField(max_length=50)),
                ('i_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=200)),
                ('warehouse_street', models.CharField(max_length=200)),
                ('warehouse_city', models.CharField(max_length=200)),
                ('warehouse_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks_qty', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.items')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.warehouse')),
            ],
        ),
    ]
